-- This is the final state of the CLI database after all migrations.
-- Auto-generated by generate-schema.go. Do not edit manually.
CREATE TABLE system
		(
			key string NOT NULL,
			value text NOT NULL
		);
CREATE TABLE nodes
			(
				id integer PRIMARY KEY AUTOINCREMENT,
				uuid text NOT NULL UNIQUE,
				parent_uuid text NOT NULL DEFAULT '',
				rank integer NOT NULL DEFAULT 0,
				name text NOT NULL DEFAULT '',
				note text NOT NULL DEFAULT '',
				type text NOT NULL DEFAULT 'bullets',
				mirror_of text NOT NULL DEFAULT '',
				completed_at integer NOT NULL DEFAULT 0,
				added_on integer NOT NULL DEFAULT 0,
				edited_on integer NOT NULL DEFAULT 0,
				deleted bool NOT NULL DEFAULT false,
				style text NOT NULL DEFAULT '', collapsed bool NOT NULL DEFAULT false, readonly bool NOT NULL DEFAULT false);
CREATE INDEX idx_nodes_parent ON nodes(parent_uuid, rank);
CREATE VIRTUAL TABLE node_fts USING fts5(content=nodes, name, note, tokenize="porter unicode61 categories 'L* N* Co Ps Pe'");
CREATE TRIGGER nodes_after_insert AFTER INSERT ON nodes BEGIN
				INSERT INTO node_fts(rowid, name, note) VALUES (new.id, new.name, new.note);
			END;
CREATE TRIGGER nodes_after_delete AFTER DELETE ON nodes BEGIN
				INSERT INTO node_fts(node_fts, rowid, name, note) VALUES ('delete', old.id, old.name, old.note);
			END;
CREATE TRIGGER nodes_after_update AFTER UPDATE ON nodes BEGIN
				INSERT INTO node_fts(node_fts, rowid, name, note) VALUES ('delete', old.id, old.name, old.note);
				INSERT INTO node_fts(rowid, name, note) VALUES (new.id, new.name, new.note);
			END;
CREATE TABLE node_output (
			uuid text PRIMARY KEY,
			output text NOT NULL DEFAULT ''
		);
CREATE TABLE chips (
			id text PRIMARY KEY,
			kind text NOT NULL DEFAULT '',
			value text NOT NULL DEFAULT ''
		, label text NOT NULL DEFAULT '');
CREATE TABLE settings (
			key text PRIMARY KEY,
			value text NOT NULL DEFAULT ''
		);

-- Migration version data.
INSERT INTO system (key, value) VALUES ('schema', 28);
