package editor

import (
	"strconv"
	"sync"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/lflow/lflow/packages/database"
)

// nodeType is the per-type descriptor — the single place a node type's editor
// behavior is declared. One file per type, registering its descriptor at init
// (registerType), plus optional render / glyph / expand funcs — instead of
// editing the scattered switches in glyphFor, renderBody, the /type picker,
// and the inline-edit guards.
//
// Cross-cutting concerns stay where they belong: the collapsed ● glyph is
// handled in glyphFor (it applies to every type); the
// legacy display attributes (heading bold, quote bar, code background) stay in
// renderBody. A rich type that wants full control of its inline body sets
// `render` (like json); a type that is read-only inline sets InlineEditable=false;
// a type with an alt+e panel sets `expand`.
type nodeType struct {
	key, label     string
	sign           string                             // inline prefix sign, e.g. "$ "; "" = none
	glyph          func(it *item) (string, string)    // per-type glyph+color; nil → default ○/●
	render         func(it *item, name string) string // stateless inline-body override; nil → default
	renderM        func(m *Model, it *item) string    // Model-aware inline-body override (voice waveform)
	inlineEditable bool                               // false → typing/backspace/enter is a no-op
	autoFocus      bool                               // resting the cursor here auto-enters its view (thin caret, type directly) — no alt+e; see reconcileAutoFocus
	blockFaces     bool                               // alt+e toggles the Render (prose) face ⇄ the BlockCode (code) face instead of entering an editor (nlpcompute); see toggleBlockFace
	tempOnly       bool                               // only offered/allowed in the Temporary Domain
	// internal keeps a type out of the /type picker: it is GENERATED by another
	// node (a search hit row), not a shape a user converts a node into. Rows of
	// it render, sync and move like any other node.
	internal     bool
	disableChips bool                             // structured chip gestures (#, >, [[, dates, $) remain literal in this type
	expand       func(m *Model, it *item) tea.Cmd // alt+e action (action-only types, e.g. voice play, file → $EDITOR)
	run          func(m *Model, it *item) tea.Cmd // alt+r action; nil → none
	view         nodeView                         // alt+e inline expanded view; nil → none
	// openHost is the alt+o action: hand the node's content to the HOST — the
	// desktop's own viewer/app, outside the terminal entirely (image → the
	// system image previewer). The terminal keeps drawing inline unicode; this
	// is the escape hatch for pixels a text cell cannot carry. nil → none.
	openHost func(m *Model, it *item) tea.Cmd
	// flashActions lets a type declare its own flash (alt+s) actions — each a verb,
	// a chip color, and a handler — so flash surfaces named, colored actions with no
	// switch in flash.go. nil → the actions are inferred from run/view/expand (a
	// generic "run"/"expand"). See flashActionsFor. jump and fold stay universal.
	flashActions func(m *Model, it *item) []flashAction

	// cliDeps lists the CLI binaries the type shells out to (NodeCLIDeps).
	// Availability is judged by the daemon (execution side); a missing dep
	// greys the type in /type and alt+r errors "Missing dependency: <bin>".
	cliDeps []string

	// bands hangs extra band lines beneath the node in the outline flow (like the
	// note / run-output bands), e.g. the image thumbnail. Called from both render
	// paths (viewRenderRows and finalView) so a banded type declares it once here
	// instead of a type check in each. nil → no extra bands.
	bands func(m *Model, r row, below bool, maxLine int) []string
	// blockCode makes the node render AS a borderless code block that REPLACES its
	// row (no glyph/body line — see viewRenderRows / blockGroupLines): it returns
	// the code, the caret rune index when the node is the focused editing target
	// (else -1), and ok=false to fall back to the normal row. nil → normal row.
	blockCode func(m *Model, it *item, focused bool) (code string, caret int, ok bool)
	// continueOnEnter makes Enter from this type open another node of the same type
	// — the todo-list continuation, where a fresh sibling stays a todo.
	continueOnEnter bool
	// onType runs right after /type has set this type on a node — the hook a type
	// uses to land on its own face instead of leaving the picker on a row that
	// looks unchanged (the Table folds to its grid face). nil → nothing.
	onType func(m *Model, it *item)
	// onRemove fires when a node of this type leaves the tree — cancel any
	// in-flight work keyed on it (nlpcompute's generation).
	onRemove func(m *Model, uuid string)

	// granular look hooks: an editable type keeps caret editing while these
	// decide its look (glyph, prefix, muted tail) — see the log type.
	prefix    func(it *item) string // styled prefix before the body, e.g. the log time chip
	baseColor func(it *item) string
	// fixedColor says baseColor is the LAST word: a /color on the node does not
	// override it. For a type whose color carries meaning (thinking is always
	// muted gray), a recolor would be the node lying about what it is.
	fixedColor bool                  // body foreground SGR; "" keeps the default
	muteFrom   func(name string) int // rune index the muted tail starts at; -1 = none
	// spanColor tints individual runes of an EDITABLE node's body without taking
	// over the whole render (unlike `render`): it returns index→SGR-color for the
	// runes to recolor, applied through the same per-rune path as magic keywords,
	// so the caret and selection still work. The Math type paints its operator
	// glyphs yellow this way. nil → no per-rune tint. (index is a rune index.)
	spanColor func(it *item, runes []rune) map[int]string
	// bodyTail appends already-styled text after the node's body on the same row
	// (before the ★ mark) — the Math type's dim linear preview of its subtree, the
	// Bash type's composed command line. The chip store comes along so a tail can
	// resolve anchors (a path chip in a command) instead of leaking sentinels.
	// Called for the resting/selected row alike. nil → nothing. "" → nothing.
	bodyTail func(it *item, chips map[string]database.Chip) string
	// runInTail says this type's run lives in the row's bodyTail — the streaming
	// headline after its "→" — and so claims NO output band beneath the row. The
	// Bash type sets it to read exactly like the cmd chip it is the tree form of:
	// the row streams, alt+e opens the terminal, nothing hangs in between.
	runInTail bool
}

// nodeView is a node type's INLINE expanded view: alt+e focuses it, its lines
// render as bands beneath the node (in the outline flow — never a separate
// screen), and while focused it captures keys. It is stateless — it receives
// (m, it) every call and keeps per-node state in m's data stores keyed by
// it.uuid — so one value serves every node of the type. This is what lets a new
// rich type plug in via one registry entry instead of a central mode.
type nodeView interface {
	// enter focuses the view (alt+e); seed any edit buffer here. false declines
	// (nothing to show), leaving focus off.
	enter(m *Model, it *item) bool
	// lines reports the total band-line count at this width, so the caller can
	// clamp the scroll offset. Pure.
	lines(m *Model, it *item, width int) int
	// bands renders the view as band lines beneath the node, self-windowed to
	// [scroll, scroll+winH). rail is the tree-rail prefix; focused draws carets.
	bands(m *Model, it *item, rail string, width, scroll, winH int, focused bool) []string
	// key handles a key while focused; handled=false falls through (esc/ctrl+c
	// are handled centrally).
	key(m *Model, it *item, k tea.KeyMsg) (tea.Cmd, bool)
	// leave is called on esc/defocus — flush the edit buffer to persisted state.
	leave(m *Model, it *item)
}

// nodeViewOf returns the inline view for an item's type, or nil.
func nodeViewOf(it *item) nodeView {
	if it == nil {
		return nil
	}
	return typeOf(it.typ).view
}

// nodeTypes is the registry the /type picker reads. Every type lives in its own
// file under this package, registering its descriptor at init (registerType);
// the table is lazily re-sorted into database.TypeOrder and indexed on first
// read, because init order across files is compiler-defined.
//
// WARNING (invariant): everything is a node with a free-string type — a NEW
// node type is a new FILE here, NOT a DB migration. nodes.type is free text
// and typeOf() falls back to bullets for unknown keys.
var nodeTypes = []nodeType{}

// registerType adds a type's descriptor to the registry.
func registerType(nt nodeType) { nodeTypes = append(nodeTypes, nt) }

// typeIndexOnce guards the lazy sort + index.
var typeIndexOnce sync.Once

// ensureTypes sorts the registry into database.TypeOrder and builds byType —
// lazily on the first lookup, because every type file registers at its own
// init and only the first READ may assume they have all run.
func ensureTypes() {
	typeIndexOnce.Do(func() {
		pos := make(map[string]int, len(database.TypeOrder))
		for i, k := range database.TypeOrder {
			pos[k] = i
		}
		sort := nodeTypes
		for i := 1; i < len(sort); i++ { // insertion sort by TypeOrder (small set)
			for j := i; j > 0 && pos[sort[j].key] < pos[sort[j-1].key]; j-- {
				sort[j], sort[j-1] = sort[j-1], sort[j]
			}
		}
		byType = make(map[string]nodeType, len(nodeTypes))
		for _, nt := range nodeTypes {
			byType[nt.key] = nt
		}
	})
}

// byType is filled by ensureTypes — a var initializer would cycle: nodeTypes
// references runQuery, which reaches typeOf/byType through the query type filter.
var byType map[string]nodeType

// RegisteredTypeKeys returns every registered node-type key (internal types
// included), in registry order. It exists for the registry-parity check:
// database.TypeOrder and this list must agree (see registry_parity_test.go).
func RegisteredTypeKeys() []string {
	ensureTypes()
	keys := make([]string, 0, len(nodeTypes))
	for _, nt := range nodeTypes {
		keys = append(keys, nt.key)
	}
	return keys
}

// typeOf returns the descriptor for a type key; unknown keys fall back to
// bullets, which is what keeps a node of a retired type (e.g. the removed
// NodeMod system's) rendering instead of crashing.
func typeOf(key string) nodeType {
	ensureTypes()
	if nt, ok := byType[key]; ok {
		return nt
	}
	return byType[database.TypeBullets]
}

// typeOrder drives the /type picker: the registry in its declared order, minus
// the internal types another node generates rather than a user chooses.
func typeOrder() []string {
	ensureTypes()
	out := make([]string, 0, len(nodeTypes))
	for _, nt := range nodeTypes {
		if nt.internal {
			continue
		}
		out = append(out, nt.key)
	}
	return out
}

// typeLabel is the picker label for a type key.
func typeLabel(key string) string {
	return typeOf(key).label
}

// removeNodeStateUnder lets types cancel in-flight work (nlpcompute's
// generation) before a subtree disappears locally or through live sync.
func (m *Model) removeNodeStateUnder(it *item) {
	if it == nil {
		return
	}
	var walk func(*item)
	walk = func(n *item) {
		if nr := typeOf(n.typ).onRemove; nr != nil {
			nr(m, n.uuid)
		}
		for _, child := range n.children {
			walk(child)
		}
	}
	walk(it)
}

// ── shared type helpers ─────────────────────────────────────────────────────

// WindowBands clamps a band list to [scroll, scroll+winH).
func WindowBands(content []string, scroll, winH int) []string {
	if scroll > len(content) {
		scroll = len(content)
	}
	end := scroll + winH
	if end > len(content) {
		end = len(content)
	}
	return content[scroll:end]
}

// codeBodyTail shows a statement/container header's folded body size:
// `· 12 lines`. Shared by the language-statement nodes (python, rust) and the
// language-neutral constructs (fn, class).
func codeBodyTail(it *item, _ map[string]database.Chip) string {
	if len(it.children) == 0 {
		return ""
	}
	lines := codeLineCount(it) - 1
	word := "lines"
	if lines == 1 {
		word = "line"
	}
	return cDim + " · " + strconv.Itoa(lines) + " " + word + cReset
}

// codeLineCount counts the lines a subtree renders to.
func codeLineCount(it *item) int {
	total := 1
	for _, c := range it.children {
		total += codeLineCount(c)
	}
	return total
}
