package editor

import (
	tea "github.com/charmbracelet/bubbletea"

	"github.com/lflow/lflow/packages/database"
)

// nodeType is the per-type descriptor — the single place a node type's editor
// behavior is declared. Adding a type = one entry here (plus optional render /
// glyph / expand funcs), instead of editing the scattered switches in glyphFor,
// renderBody, the /type picker, and the inline-edit guards.
//
// Cross-cutting concerns stay where they belong: the collapsed ● glyph is
// handled in glyphFor (it applies to every type); the
// legacy display attributes (heading bold, quote bar, code background) stay in
// renderBody. A rich type that wants full control of its inline body sets
// `render` (like json); a type that is read-only inline sets InlineEditable=false;
// a type with an alt+e panel sets `expand`.
type nodeType struct {
	key, label     string
	sign           string                             // inline prefix sign, e.g. "$ "; "" = none
	glyph          func(it *item) (string, string)    // per-type glyph+color; nil → default ○/●
	render         func(it *item, name string) string // stateless inline-body override; nil → default
	renderM        func(m *Model, it *item) string    // Model-aware inline-body override (voice waveform)
	inlineEditable bool                               // false → typing/backspace/enter is a no-op
	autoFocus      bool                               // resting the cursor here auto-enters its view (thin caret, type directly) — no alt+e; see reconcileAutoFocus
	blockFaces     bool                               // alt+e toggles the Render (prose) face ⇄ the BlockCode (code) face instead of entering an editor (nlpcompute); see toggleBlockFace
	tempOnly       bool                               // only offered/allowed in the Temporary Domain
	// internal keeps a type out of the /type picker: it is GENERATED by another
	// node (a search hit row), not a shape a user converts a node into. Rows of
	// it render, sync and move like any other node.
	internal     bool
	disableChips bool                             // structured chip gestures (#, >, [[, dates, $) remain literal in this type
	expand       func(m *Model, it *item) tea.Cmd // alt+e action (action-only types, e.g. voice play, file → $EDITOR)
	run          func(m *Model, it *item) tea.Cmd // alt+r action; nil → none
	view         nodeView                         // alt+e inline expanded view; nil → none
	// openHost is the alt+o action: hand the node's content to the HOST — the
	// desktop's own viewer/app, outside the terminal entirely (image → the
	// system image previewer). The terminal keeps drawing inline unicode; this
	// is the escape hatch for pixels a text cell cannot carry. nil → none.
	openHost func(m *Model, it *item) tea.Cmd
	// flashActions lets a type declare its own flash (alt+s) actions — each a verb,
	// a chip color, and a handler — so flash surfaces named, colored actions with no
	// switch in flash.go. nil → the actions are inferred from run/view/expand (a
	// generic "run"/"expand"). See flashActionsFor. jump and fold stay universal.
	flashActions func(m *Model, it *item) []flashAction

	// cliDeps lists the CLI binaries the type shells out to (NodeCLIDeps).
	// Availability is judged by the daemon (execution side); a missing dep
	// greys the type in /type and alt+r errors "Missing dependency: <bin>".
	cliDeps []string

	// bands hangs extra band lines beneath the node in the outline flow (like the
	// note / run-output bands), e.g. the image thumbnail. Called from both render
	// paths (viewRenderRows and finalView) so a banded type declares it once here
	// instead of a type check in each. nil → no extra bands.
	bands func(m *Model, r row, below bool, maxLine int) []string
	// blockCode makes the node render AS a borderless code block that REPLACES its
	// row (no glyph/body line — see viewRenderRows / blockGroupLines): it returns
	// the code, the caret rune index when the node is the focused editing target
	// (else -1), and ok=false to fall back to the normal row. nil → normal row.
	blockCode func(m *Model, it *item, focused bool) (code string, caret int, ok bool)
	// continueOnEnter makes Enter from this type open another node of the same type
	// — the todo-list continuation, where a fresh sibling stays a todo.
	continueOnEnter bool
	// onType runs right after /type has set this type on a node — the hook a type
	// uses to land on its own face instead of leaving the picker on a row that
	// looks unchanged (the Table folds to its grid face). nil → nothing.
	onType func(m *Model, it *item)

	// granular look hooks: an editable type keeps caret editing while these
	// decide its look (glyph, prefix, muted tail) — see the log type.
	prefix    func(it *item) string // styled prefix before the body, e.g. the log time chip
	baseColor func(it *item) string
	// fixedColor says baseColor is the LAST word: a /color on the node does not
	// override it. For a type whose color carries meaning (thinking is always
	// muted gray), a recolor would be the node lying about what it is.
	fixedColor bool                  // body foreground SGR; "" keeps the default
	muteFrom   func(name string) int // rune index the muted tail starts at; -1 = none
	// spanColor tints individual runes of an EDITABLE node's body without taking
	// over the whole render (unlike `render`): it returns index→SGR-color for the
	// runes to recolor, applied through the same per-rune path as magic keywords,
	// so the caret and selection still work. The Math type paints its operator
	// glyphs yellow this way. nil → no per-rune tint. (index is a rune index.)
	spanColor func(it *item, runes []rune) map[int]string
	// bodyTail appends already-styled text after the node's body on the same row
	// (before the ★ mark) — the Math type's dim linear preview of its subtree, the
	// Bash type's composed command line. The chip store comes along so a tail can
	// resolve anchors (a path chip in a command) instead of leaking sentinels.
	// Called for the resting/selected row alike. nil → nothing. "" → nothing.
	bodyTail func(it *item, chips map[string]database.Chip) string
	// runInTail says this type's run lives in the row's bodyTail — the streaming
	// headline after its "→" — and so claims NO output band beneath the row. The
	// Bash type sets it to read exactly like the cmd chip it is the tree form of:
	// the row streams, alt+e opens the terminal, nothing hangs in between.
	runInTail bool
}

// nodeView is a node type's INLINE expanded view: alt+e focuses it, its lines
// render as bands beneath the node (in the outline flow — never a separate
// screen), and while focused it captures keys. It is stateless — it receives
// (m, it) every call and keeps per-node state in m's data stores keyed by
// it.uuid — so one value serves every node of the type. This is what lets a new
// rich type plug in via one registry entry instead of a central mode.
type nodeView interface {
	// enter focuses the view (alt+e); seed any edit buffer here. false declines
	// (nothing to show), leaving focus off.
	enter(m *Model, it *item) bool
	// lines reports the total band-line count at this width, so the caller can
	// clamp the scroll offset. Pure.
	lines(m *Model, it *item, width int) int
	// bands renders the view as band lines beneath the node, self-windowed to
	// [scroll, scroll+winH). rail is the tree-rail prefix; focused draws carets.
	bands(m *Model, it *item, rail string, width, scroll, winH int, focused bool) []string
	// key handles a key while focused; handled=false falls through (esc/ctrl+c
	// are handled centrally).
	key(m *Model, it *item, k tea.KeyMsg) (tea.Cmd, bool)
	// leave is called on esc/defocus — flush the edit buffer to persisted state.
	leave(m *Model, it *item)
}

// nodeViewOf returns the inline view for an item's type, or nil.
func nodeViewOf(it *item) nodeView {
	if it == nil {
		return nil
	}
	return typeOf(it.typ).view
}

// nodeTypes is the ordered registry; the /type picker shows it in this order.
//
// WARNING (invariant): everything is a node with a free-string type — a NEW node
// type is a new entry here (plus its descriptor), NOT a DB migration. nodes.type
// is free text and typeOf() falls back to bullets for unknown keys.
var nodeTypes = []nodeType{
	{
		key: database.TypeVoice, label: "Voice", inlineEditable: false,
		renderM:      func(m *Model, it *item) string { return m.voiceRender(it) },
		run:          runVoice,
		expand:       playVoice,
		flashActions: voiceFlashActions, // name them: "record" (toggle) and "play"
		cliDeps:      []string{"ffmpeg"},
	},
	{
		// an image: alt+r pastes from the host clipboard, alt+e opens the half-block
		// preview, alt+o hands the PNG to the desktop's own image viewer. The
		// pixels are a PNG blob in node_blobs keyed by node uuid — so the outline
		// stays one portable SQLite file; the name holds an optional caption.
		key: database.TypeImage, label: "Image", inlineEditable: false,
		renderM:      func(m *Model, it *item) string { return m.imageRender(it) },
		run:          runImagePaste,
		view:         imageView{},   // alt+e: scrollable half-block render
		openHost:     imageOpenHost, // alt+o: the host's image viewer
		flashActions: imageFlashActions,
		bands:        func(m *Model, r row, below bool, maxLine int) []string { return m.imageBandLines(r, below, maxLine) },
	},
	// a math expression composed as an outline (see math.go): the node's text is
	// an operator (colored yellow) with operands as children, or an atom leaf.
	// Stays inline-editable; the operator row carries a dim linear preview of its
	// whole subtree, and children fan out as the AST beneath it.
	// markup composed as an outline (see markup.go): the node's text is a tag
	// with its attributes and its children are its child elements. Both stay
	// inline-editable; a known tag tints accent, attribute names dim, and an
	// element row carries a dim linear preview of the document beneath it.
	{
		key: database.TypeSVG, label: "SVG", inlineEditable: true, continueOnEnter: true,
		onType:       markupOnType,
		run:          runSVGRender, // alt+r: rasterize the subtree into the node's picture
		view:         markupView{}, // alt+e: the picture once rendered, else the document
		flashActions: svgFlashActions,
		bands:        func(m *Model, r row, below bool, maxLine int) []string { return m.svgBandLines(r, below, maxLine) },
		// deliberately no cliDeps: there is no ONE binary this needs. It tries
		// several rasterizers in turn (see svgRasterizers), so declaring the
		// preferred one would warn "missing dependency" on a machine where the
		// node works perfectly through the next one down.
	},
	{
		key: database.TypeHTML, label: "HTML", inlineEditable: true, continueOnEnter: true,
		onType:       markupOnType,
		run:          runHTMLOut,   // alt+r: the serialized markup into the run band
		view:         markupView{}, // alt+e: the whole document the row shows the head of
		flashActions: htmlFlashActions,
		runInTail:    true,
	},
	// a table is an ordinary subtree READ as a grid (see table.go): columns are
	// the children, rows are their children, and a cell's children are the
	// outline inside it. The face IS the fold state — a folded table draws its
	// grid, an open one is the plain outline — so ctrl+space / alt+↑↓ toggle
	// table ⇄ nodes, and alt+e opens the grid editor.
	{
		key: database.TypeTable, label: "Table", inlineEditable: true,
		glyph:        tableGlyph,
		bands:        func(m *Model, r row, below bool, maxLine int) []string { return m.tableBandLines(r, below, maxLine) },
		view:         tableView{},
		flashActions: tableFlashActions,
		onType:       tableOnType,
	},
	// a molecule is an ordinary subtree READ as a structure: one atom per node,
	// the bond to the parent as a prefix (=O), children the atoms bonded to it —
	// so the outline IS the molecular graph, the way the Math node is the AST.
	// alt+e draws it. A notation string mentioned inline is a ⌬ chip instead.
	{
		key: database.TypeMol, label: "Molecule", inlineEditable: true,
		glyph:     moleculeGlyph,
		spanColor: molSpanColor,
		bodyTail:  molTreeBodyTail,
		view:      moleculeView{},
		// building a molecule as an outline is atom-after-atom, so Enter keeps the
		// type going (the todo-list continuation) — otherwise every second atom
		// would land as a bullet and need retyping.
		continueOnEnter: true,
	},
	// a mirrored Zotero entry (see zoteroitem.go): the paper itself in the tree,
	// its tags on the title row and its attachments, annotations and notes as
	// locked children. Never inline-editable — the subtree is Zotero's, and
	// alt+r re-reads it. Every node of the mirror wears this type; the binding
	// in zotero_nodes says which Zotero object each one stands for.
	{
		key: database.TypeZotero, label: "Zotero", inlineEditable: false,
		glyph:        zoteroGlyph,
		run:          runZoteroPull, // alt+r: re-read the entry, or pick one on an unbound node
		flashActions: zoteroFlashActions,
		bodyTail: func(it *item, chips map[string]database.Chip) string {
			// an unbound zotero node (edge case) reads as a prompt, not a blank row
			if _, ok := zoteroBindingFor(it); ok {
				return ""
			}
			return cDim + "pick a Zotero entry · alt+r" + cReset
		},
	},
	// The pluggable node types (fn, class, comment, text, nlpcompute — see
	// packages/nodes; python, rust — see packages/fileeditor) register through
	// nodes.Register at init and fold in lazily; see ensurePlugins.
}

// byType fills in init() — a var initializer would cycle: nodeTypes references
// runQuery, which reaches typeOf/byType through the query type filter.
var byType map[string]nodeType

func init() {
	byType = make(map[string]nodeType, len(nodeTypes))
	for _, nt := range nodeTypes {
		byType[nt.key] = nt
	}
}

// RegisteredTypeKeys returns every registered node-type key (built-ins plus
// plugins, internal types included), in registry order. It exists for the
// registry-parity check: database.TypeOrder and this list must agree, and a
// test in packages/nodes (the one package that links both sides) enforces it.
func RegisteredTypeKeys() []string {
	ensurePlugins()
	keys := make([]string, 0, len(nodeTypes))
	for _, nt := range nodeTypes {
		keys = append(keys, nt.key)
	}
	return keys
}

// typeOf returns the descriptor for a type key; unknown keys fall back to
// bullets, which is what keeps a node of a retired type (e.g. the removed
// NodeMod system's) rendering instead of crashing.
func typeOf(key string) nodeType {
	ensurePlugins()
	if nt, ok := byType[key]; ok {
		return nt
	}
	return byType[database.TypeBullets]
}

// typeOrder drives the /type picker: the registry in its declared order, minus
// the internal types another node generates rather than a user chooses.
func typeOrder() []string {
	ensurePlugins()
	out := make([]string, 0, len(nodeTypes))
	for _, nt := range nodeTypes {
		if nt.internal {
			continue
		}
		out = append(out, nt.key)
	}
	return out
}

// typeLabel is the picker label for a type key.
func typeLabel(key string) string {
	return typeOf(key).label
}
